name: FlirrtApp
options:
  bundleIdPrefix: ai.flirrt
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "16.0"

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "18.0"
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  FlirrtApp:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: FlirrtApp
        excludes:
          - "*.entitlements"
          - "Info.plist"
      - path: Shared
    resources:
      - FlirrtApp/Assets.xcassets
      - FlirrtApp/Preview Content
    info:
      path: FlirrtApp/Info.plist
      properties:
        CFBundleDisplayName: Flirrt
        CFBundleIdentifier: ai.flirrt.FlirrtApp
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: FlirrtApp/FlirrtApp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.ai.flirrt.shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ai.flirrt.FlirrtApp
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_PREVIEWS: true
      DEVELOPMENT_ASSET_PATHS: "FlirrtApp/Preview Content"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SWIFT_EMIT_LOC_STRINGS: true
      GENERATE_INFOPLIST_FILE: false
    dependencies:
      - target: FlirrtKeyboard
        embed: true

  FlirrtKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: FlirrtKeyboard
        excludes:
          - "*.entitlements"
          - "Info.plist"
      - path: Shared
        includes:
          - AppGroupCommunicator.swift
    info:
      path: FlirrtKeyboard/Info.plist
      properties:
        CFBundleDisplayName: Flirrt
        CFBundleIdentifier: ai.flirrt.FlirrtApp.FlirrtKeyboard
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).KeyboardViewController
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en-US
            RequestsOpenAccess: true
    entitlements:
      path: FlirrtKeyboard/FlirrtKeyboard.entitlements
      properties:
        com.apple.security.application-groups:
          - group.ai.flirrt.shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ai.flirrt.FlirrtApp.FlirrtKeyboard
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      SKIP_INSTALL: true
      SWIFT_EMIT_LOC_STRINGS: true
      GENERATE_INFOPLIST_FILE: false

schemes:
  FlirrtApp:
    build:
      targets:
        FlirrtApp: all
        FlirrtKeyboard: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

